-- USER SQL
ALTER USER "SILOKO"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "SILOKO" DEFAULT ROLE "DBA","CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
